############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Blog
  url: /blog/
  weight: 20
- name: CTF
  url: /ctf/
  weight: 30
- name: Whoami
  url: /about/
  weight: 40