############################
## Author
############################

author:
  name: Richie-Havoc
  image: author.png
  greeting: "Ethical Hacker | Security Researcher | Developer | Pentester | CTF Player :tada:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/Daniel-wambua/blogz
  - link: https://github.com/Daniel-wambua/blogz#readme
  - signal: https://signal.me/#eu/N2acU1DF0_iC_eFAJ-zg32OfVaLiRwts-HlDEQ1elCfAvfi4261Bh49PbPhwzZFQ
  - website: https://havocsec.tech
  - linkedin: https://www.linkedin.com/in/daniel-wambua-a312b32b8/
  - whatsapp: +254 111 976984
  - telegram: +254 111 976984
  # - x-twitter: 
  # - mastodon:  
  # - instagram: 
  # - reddit: 
  # - telegram: +254 111 976984
  # - whatsapp: +254 111 976984
  # - codepen: 
  # - dev: 
  # - email: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: blogz
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
